/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js'

const components = [
  Button
]

const install = function (Vue, opts = {}) {
  components.forEach(component => Vue.component(component.name, component))
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.vue) {
  install(window.vue)
}

export default {
  version: '0.0.3',
  install,
  Button
}
